$schema: 'http://json-schema.org/draft-07/schema#'
definitions:
  person:
    type: 'object'
    properties:
      first:
        title: 'First'
        type: 'string'
      last:
        title: 'Last'
        type: 'string'
      relation:
        title: 'Relationship'
        type: 'string'
      phone:
        title: 'Phone number'
        type: 'string'
